export const types = {
  onBoardFinished: 'onBoardFinished',
  isLoadingTrue: 'isLoadingTrue',
  isLoadingFalse: 'isLoadingFalse',
  isAlertTrue: 'isAlertTrue',
  isAlertFalse: 'isAlertFalse',
  LoginType: 'LoginType',
  LogoutType: 'LogoutType',
  LogoutFirebaseType: 'LogoutFirebaseType',
  RegisterUser: 'RegisterUser',
  UpdateAuth: 'UpdateAuth',
  trainingCat: 'trainingCat',
  subCat: 'subCat',
  updateCat: 'updateCat',
  msdsSheet: 'msdsSheet',
  getcatalogData: 'getcatalogData',
  UpdateProfile: 'UpdateProfile',
};
